/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    teams: Team;
    matches: Match;
    players: Player;
    'player-match-stats': PlayerMatchStat;
    articles: Article;
    'gallery-images': GalleryImage;
    videos: Video;
    subscribers: Subscriber;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    matches: MatchesSelect<false> | MatchesSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    'player-match-stats': PlayerMatchStatsSelect<false> | PlayerMatchStatsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'gallery-images': GalleryImagesSelect<false> | GalleryImagesSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'en' | 'en'[];
  globals: {
    gallery: Gallery;
  };
  globalsSelect: {
    gallery: GallerySelect<false> | GallerySelect<true>;
  };
  locale: 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers, e.g. "APR FC club crest".
   */
  alt: string;
  /**
   * Optional caption for galleries and articles.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    crest?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  /**
   * Full club name, e.g. "Gor Mahia FC"
   */
  name: string;
  /**
   * URL identifier, e.g. "gor-mahia"
   */
  slug: string;
  /**
   * Abbreviation for tight layouts, e.g. "GOR"
   */
  shortName: string;
  country: 'RW' | 'UG' | 'KE' | 'TZ' | 'ZNZ' | 'SO' | 'SS' | 'SD' | 'DJ';
  group: 'A' | 'B' | 'C';
  /**
   * Club badge — square PNG with transparency preferred.
   */
  crest?: (number | null) | Media;
  /**
   * CECAFA tiebreaker 7. Leave empty. Only fill this in if officials physically draw lots to separate teams level on every other criterion — lower number ranks higher.
   */
  drawOfLotsRank?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Enter a scoreline once and set status to Final. Standings, goal difference and the best-runner-up race are all derived from this — never edited by hand.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches".
 */
export interface Match {
  id: number;
  /**
   * Auto-generated for the admin list view.
   */
  label?: string | null;
  /**
   * Official fixture number, 1–22.
   */
  matchNumber: number;
  stage: 'group' | 'semi' | 'third' | 'final';
  /**
   * Only group-stage matches count toward a group table.
   */
  group?: ('A' | 'B' | 'C') | null;
  /**
   * Leave empty for knockout fixtures until the group stage resolves — the placeholder below is shown instead.
   */
  homeTeam?: (number | null) | Team;
  awayTeam?: (number | null) | Team;
  /**
   * Shown when no team is set yet, e.g. "Winner Gr. B".
   */
  homeTeamPlaceholder?: string | null;
  /**
   * e.g. "Best Runner-Up".
   */
  awayTeamPlaceholder?: string | null;
  venue: 'amahoro' | 'pele';
  /**
   * Local Kigali time (CAT, UTC+2).
   */
  kickoff: string;
  /**
   * Only matches marked Final are counted in the standings.
   */
  status: 'scheduled' | 'live' | 'final';
  homeScore?: number | null;
  awayScore?: number | null;
  /**
   * Where the header's LIVE button sends visitors once this match is live — defaults to this match's own page automatically, or enter an external stream link instead.
   */
  liveMatchUrl?: string | null;
  /**
   * Show the site-wide header LIVE button once this match is live. A match automatically counts as live from its kickoff time (or you can set Status to Live yourself). Turn this off to keep the button hidden regardless.
   */
  showLiveButton?: boolean | null;
  /**
   * Everything that happens in the match, in order. Goals, cards and substitutions post here with the matching graphic on the Live Expressions feed — no need to duplicate them in Player Match Stats. A photo can optionally be attached to any entry.
   */
  commentary?:
    | {
        /**
         * Match minute, e.g. 62. Entries are shown in minute order on the feed.
         */
        minute?: number | null;
        /**
         * Determines which icon/graphic this entry shows with on the feed.
         */
        type?: ('note' | 'goal' | 'yellow' | 'red' | 'substitution') | null;
        /**
         * Which side this happened for.
         */
        team?: ('home' | 'away') | null;
        /**
         * Who scored or was booked.
         */
        player?: (number | null) | Player;
        /**
         * Player being substituted off.
         */
        playerOff?: (number | null) | Player;
        /**
         * Player coming on.
         */
        playerOn?: (number | null) | Player;
        /**
         * e.g. "Good save from the keeper, corner to APR." Optional extra detail for a goal/card/substitution — those already get an automatic caption from the fields above.
         */
        text?: string | null;
        /**
         * Optional photo shown with this update.
         */
        image?: (number | null) | Media;
        /**
         * Hide this entry from the public Live Expressions feed without deleting it.
         */
        hidden?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * YouTube link for the highlights section.
   */
  highlightUrl?: string | null;
  highlightThumb?: (number | null) | Media;
  /**
   * Shown in the Match Photos tab and interspersed through the live commentary feed on the match page.
   */
  photos?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Starting XI, substitutes and coach for the home team.
   */
  homeLineup?: {
    /**
     * This team's head coach for the match (optional).
     */
    coach?: string | null;
    /**
     * Up to 11 players. Drag to reorder; the order shown here is the display order.
     */
    startingXI?:
      | {
          player: number | Player;
          isCaptain?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Bench players for this match. Drag a row here from Starting XI (or back) to move it.
     */
    substitutes?:
      | {
          player: number | Player;
          isCaptain?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Starting XI, substitutes and coach for the away team.
   */
  awayLineup?: {
    /**
     * This team's head coach for the match (optional).
     */
    coach?: string | null;
    /**
     * Up to 11 players. Drag to reorder; the order shown here is the display order.
     */
    startingXI?:
      | {
          player: number | Player;
          isCaptain?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Bench players for this match. Drag a row here from Starting XI (or back) to move it.
     */
    substitutes?:
      | {
          player: number | Player;
          isCaptain?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  name: string;
  team: number | Team;
  position: 'GK' | 'CB' | 'LB' | 'RB' | 'CDM' | 'CM' | 'CAM' | 'LW' | 'RW' | 'ST';
  shirtNumber?: number | null;
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Record what each player did in a given match.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-match-stats".
 */
export interface PlayerMatchStat {
  id: number;
  player: number | Player;
  match: number | Match;
  goals: number;
  assists: number;
  /**
   * Goalkeepers and defenders who finished a match without conceding.
   */
  cleanSheet?: boolean | null;
  minutes?: number | null;
  /**
   * Feeds CECAFA fair-play points (tiebreaker 6). Record every card.
   */
  yellowCards: number;
  redCards: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * External news links shown on the site. Editors control the image, headline, blurb, destination URL, ordering and visibility — clicking a card opens the external story.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  /**
   * The headline shown on the news card.
   */
  title: string;
  /**
   * Auto-generated from the title. Used only for the internal link that redirects to the external URL.
   */
  slug?: string | null;
  /**
   * Card image (16:9 works best).
   */
  featuredImage: number | Media;
  /**
   * One or two sentences — the excerpt shown under the headline.
   */
  shortDescription: string;
  /**
   * Where the reader is taken when they click the article.
   */
  externalUrl: string;
  /**
   * Optional tag shown on the card, e.g. "Analysis", "Interview".
   */
  category?: string | null;
  /**
   * Approximate read time shown as "X min read".
   */
  readingMinutes?: number | null;
  /**
   * Featured articles lead the news sections.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first (within the same featured group).
   */
  displayOrder?: number | null;
  /**
   * Hide an article without deleting it.
   */
  visibility: 'visible' | 'hidden';
  /**
   * Shown as the article date and used for ordering.
   */
  publishDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gallery albums shown on /gallery, newest first. Each entry is a cover photo that redirects to its Flickr album when clicked.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images".
 */
export interface GalleryImage {
  id: number;
  /**
   * Album title (shown here in the admin list only — not displayed on the public site).
   */
  title: string;
  /**
   * The preview photo shown on the /gallery grid. Its alt text comes from the uploaded image.
   */
  image: number | Media;
  /**
   * Which gallery folder this album belongs to.
   */
  category: 'Action' | 'Match Day' | 'Trophy' | 'Fans' | 'Stadium' | 'APR FC';
  /**
   * The Flickr album this cover photo links to. Visitors are redirected here when they click the gallery item. Leave blank to keep the cover photo on the grid but not clickable.
   */
  flickrAlbumUrl?: string | null;
  /**
   * Optional internal note about this album (not shown on the public site).
   */
  description?: string | null;
  /**
   * Show this album on the public /gallery page. Uncheck to hide it without deleting it. Visible albums are listed newest-added first.
   */
  visible?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Clips shown in the homepage Highlights carousel, newest-added first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  /**
   * e.g. "APR FC vs Vipers SC — Extended Highlights" or "Press Conference Ahead of CECAFA".
   */
  title: string;
  /**
   * Optional short label shown under the title, e.g. "Fri 24 Jul".
   */
  dateLabel?: string | null;
  /**
   * The preview photo shown on the card.
   */
  thumbnail?: (number | null) | Media;
  /**
   * YouTube/highlight link. Leave blank for a static card with no link.
   */
  videoUrl?: string | null;
  /**
   * Show this video in the Highlights carousel. Uncheck to hide it without deleting it.
   */
  visible?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'matches';
        value: number | Match;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'player-match-stats';
        value: number | PlayerMatchStat;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'gallery-images';
        value: number | GalleryImage;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        crest?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortName?: T;
  country?: T;
  group?: T;
  crest?: T;
  drawOfLotsRank?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches_select".
 */
export interface MatchesSelect<T extends boolean = true> {
  label?: T;
  matchNumber?: T;
  stage?: T;
  group?: T;
  homeTeam?: T;
  awayTeam?: T;
  homeTeamPlaceholder?: T;
  awayTeamPlaceholder?: T;
  venue?: T;
  kickoff?: T;
  status?: T;
  homeScore?: T;
  awayScore?: T;
  liveMatchUrl?: T;
  showLiveButton?: T;
  commentary?:
    | T
    | {
        minute?: T;
        type?: T;
        team?: T;
        player?: T;
        playerOff?: T;
        playerOn?: T;
        text?: T;
        image?: T;
        hidden?: T;
        id?: T;
      };
  highlightUrl?: T;
  highlightThumb?: T;
  photos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  homeLineup?:
    | T
    | {
        coach?: T;
        startingXI?:
          | T
          | {
              player?: T;
              isCaptain?: T;
              id?: T;
            };
        substitutes?:
          | T
          | {
              player?: T;
              isCaptain?: T;
              id?: T;
            };
      };
  awayLineup?:
    | T
    | {
        coach?: T;
        startingXI?:
          | T
          | {
              player?: T;
              isCaptain?: T;
              id?: T;
            };
        substitutes?:
          | T
          | {
              player?: T;
              isCaptain?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  name?: T;
  team?: T;
  position?: T;
  shirtNumber?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-match-stats_select".
 */
export interface PlayerMatchStatsSelect<T extends boolean = true> {
  player?: T;
  match?: T;
  goals?: T;
  assists?: T;
  cleanSheet?: T;
  minutes?: T;
  yellowCards?: T;
  redCards?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featuredImage?: T;
  shortDescription?: T;
  externalUrl?: T;
  category?: T;
  readingMinutes?: T;
  featured?: T;
  displayOrder?: T;
  visibility?: T;
  publishDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images_select".
 */
export interface GalleryImagesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  category?: T;
  flickrAlbumUrl?: T;
  description?: T;
  visible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  dateLabel?: T;
  thumbnail?: T;
  videoUrl?: T;
  visible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The banner image at the top of the /gallery page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  /**
   * Banner image across the top of the /gallery page.
   */
  heroImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}